set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"
set -g status on
set -g status-style "bg=#2e3436,fg=#d3d7cf"
set -g status-left-style "bg=#3465a4,fg=#eeeeec,bold"
set -g status-right-style "bg=#2e3436,fg=#babdb6"
set -g status-left " #[fg=#eeeeec]#S "
set -g status-right " %H:%M "
set -g window-status-current-style "bg=#555753,fg=#eeeeec,bold"
set -g window-status-style "bg=#2e3436,fg=#babdb6"
set -g pane-border-style "fg=#555753"
set -g pane-active-border-style "fg=#729fcf"
set -g message-style "bg=#3465a4,fg=#eeeeec"
set -g mode-style "bg=#3465a4,fg=#eeeeec"
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " #I:#W "
set -g status-interval 2
set -g mouse off
set -g history-limit 5000
