# =============================================================================
# PROFILE 03 — 有认证，但 ACL 过宽（# 全开）
# 用途：主题遍历 / 横向读敏感主题
# =============================================================================

per_listener_settings true

listener 1883 0.0.0.0
protocol mqtt
allow_anonymous false
password_file /etc/mosquitto/lab/passwd
acl_file /etc/mosquitto/lab/acl/wide.acl

listener 9001 0.0.0.0
protocol websockets
allow_anonymous false
password_file /etc/mosquitto/lab/passwd
acl_file /etc/mosquitto/lab/acl/wide.acl

sys_interval 10
