# =============================================================================
# PROFILE 04 — 认证 + 最小 ACL（加固对照）
# 用途：同样账号，敏感主题读不到 / 写不进去
# =============================================================================

per_listener_settings true

listener 1883 0.0.0.0
protocol mqtt
allow_anonymous false
password_file /etc/mosquitto/lab/passwd
acl_file /etc/mosquitto/lab/acl/strict.acl

listener 9001 0.0.0.0
protocol websockets
allow_anonymous false
password_file /etc/mosquitto/lab/passwd
acl_file /etc/mosquitto/lab/acl/strict.acl

sys_interval 10
